### PR TITLE
feat: add token faucet

### PR DESCRIPTION
**Pull request by michael1011**
WIP and not tested yet

But I would love to some feedback [here](https://github.com/ExchangeUnion/xud-simnet-bot/compare/faucet?expand=1#diff-b6a4578644ff758f64d3693a3025da8dL21) and on [this logic](https://github.com/ExchangeUnion/xud-simnet-bot/compare/faucet?expand=1#diff-9ff6122cb7c0ddb43ed9298e02eb7623R37) before continuing with my current approach.

Also one minor thing: right now the REST API endpoint is on HTTP. Should I make it work natively over HTTPS, do we want to run some Nginx reverse proxy or are we fine with HTTP for the faucet?

### CODE REVIEW

**Comment by kilrau** [comment]
+1 for https, even though not the most important thing in the world rn

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Looks good, conceptually.

**Review by sangaman — APPROVED** [review]
The code and concept looks good. The only thing I think that may make sense at some point is some basic rate limiting (by IP and/or address) but otherwise this looks clean and straightforward.

**Comment by michael1011** [comment]
Sample config for the faucet:
```
[[channels]]
currency = "ETH"
amount = 2.5

[[channels]]
currency = "TOKEN"
tokenAddress = "0x4A1BF5BA9A7Ee20e527C8A015DDb4B469135B146"
amount = 20.0
```

**Pull request merged**
